# Generated by Django 5.1.3 on 2025-04-10 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('products', '0003_comparison_favorite_productreview_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=12, unique=True, verbose_name='Номер заказа')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('stage', models.CharField(choices=[('Stage_1', 'Подготовка документов'), ('Stage_2', 'Внесение аванса'), ('Stage_3', 'Выдача товара'), ('Stage_4', 'Заказ отгружен')], default='Stage_1', max_length=7, verbose_name='Этап заказа')),
                ('payment_type', models.CharField(choices=[('is_leasing', 'Лизинг'), ('is_cash', 'Безналичный расчет')], max_length=10, verbose_name='Тип оплаты')),
                ('down_payment_percent', models.IntegerField(default=10, verbose_name='Первоначальный взнос, %')),
                ('company_for_leasing', models.TextField(blank=True, default=None, null=True, verbose_name='Организация для лизинга')),
                ('first_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма первоначального взноса')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма заказа')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('delivery_number', models.CharField(blank=True, db_index=True, max_length=12, unique=True, verbose_name='Номер доставки')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company', verbose_name='Организация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product', verbose_name='Товар')),
                ('selected_additional_options', models.ManyToManyField(blank=True, to='products.additionaloption', verbose_name='Выбранные опции')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=12, unique=True, verbose_name='Номер заказа')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('delivery_stage', models.CharField(choices=[('Stage_1', 'Ожидание оплаты'), ('Stage_2', 'В пути'), ('Stage_3', 'Отгрузка'), ('Cancel', 'Отмена')], default='Stage_1', max_length=100, verbose_name='Этап заказа')),
                ('delivery_type', models.CharField(choices=[('trall', 'Тралл'), ('train', 'ЖД'), ('sea', 'Море'), ('self', 'Своим ходом')], default='trall', max_length=100, verbose_name='Тип доставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма заказа')),
                ('dimensions', models.CharField(default='', max_length=255, verbose_name='Габариты')),
                ('date_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('address_delivery', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='products.product', verbose_name='Товар')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_companies', to='account.company', verbose_name='Компания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доставка заказа',
                'verbose_name_plural': 'Доставки заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата назначения')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignment', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Назначение менеджера',
                'verbose_name_plural': 'Назначения менеджеров',
            },
        ),
    ]
