# Generated by Django 5.1.3 on 2025-04-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_leasing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма покупки на лизинг'),
        ),
        migrations.AddField(
            model_name='order',
            name='count_of_contracts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество контрактов'),
        ),
        migrations.AddField(
            model_name='order',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Оборот'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_set', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
