# Generated by Django 5.1.3 on 2025-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_amount_of_leasing_order_count_of_contracts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Название банка')),
                ('max_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Максимальная сумма лизинга')),
                ('percentage_year', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Удорожание в год в процентах')),
                ('first_installment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Первоначального взноса в процентах')),
                ('logo', models.ImageField(upload_to='banks', verbose_name='Логотип банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
    ]
