# Generated by Django 5.1.3 on 2025-04-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bank_order_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='order',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
    ]
