# Generated by Django 5.1.3 on 2025-04-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_bank_order_remove_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_for_leasing',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_for_leasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.bank', verbose_name='Банк для лизинга'),
        ),
    ]
