# Generated by Django 5.1.3 on 2025-04-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_company_for_leasing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк для лизинга', 'verbose_name_plural': 'Банки для лизинга'},
        ),
    ]
