# Generated by Django 5.1.3 on 2025-04-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_bank_options'),
        ('products', '0004_alter_additionaloption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='dimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dimensions', verbose_name='Габариты'),
        ),
    ]
