# Generated by Django 5.1.3 on 2025-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_release',
            field=models.IntegerField(default=2025, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=2025, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
