# Generated by Django 5.1.3 on 2025-04-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comparison_favorite_productreview_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaloption',
            options={'verbose_name': 'Дополнительная опция', 'verbose_name_plural': 'Дополнительные опции'},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comparison',
            options={'verbose_name': 'Сравнение товаров', 'verbose_name_plural': 'Сравнения товаров'},
        ),
        migrations.AlterModelOptions(
            name='dimensions',
            options={'verbose_name': 'Габариты товара', 'verbose_name_plural': 'Габариты товара'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'История цен', 'verbose_name_plural': 'Истории цен'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
        migrations.AlterModelOptions(
            name='productdocument',
            options={'verbose_name': 'Документация товара', 'verbose_name_plural': 'Документации товара'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товара'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Отзыв по товару', 'verbose_name_plural': 'Отзывы по товару'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
