# Generated by Django 5.1.3 on 2025-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_additionaloption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='cur_price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Последняя цена'),
        ),
    ]
