# Generated by Django 5.1.3 on 2025-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_product_cur_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_price',
        ),
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Предыдущая цена'),
        ),
    ]
