# Generated by Django 5.1.3 on 2025-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_last_price_product_prev_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='product',
        ),
        migrations.AddField(
            model_name='comparison',
            name='products',
            field=models.ManyToManyField(related_name='comparisons', to='products.product', verbose_name='Продукты'),
        ),
    ]
