# Generated by Django 5.1.3 on 2025-04-25 11:48

import django.db.models.deletion
import products.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_deliveryorder_dimensions'),
        ('products', '0007_remove_comparison_product_comparison_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='visible',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('moderation', 'Модерация'), ('approved', 'Утвержден'), ('rejected', 'Отклонен')], default='new', max_length=10, verbose_name='Статус отзыва'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='cons',
            field=models.TextField(blank=True, null=True, verbose_name='Минусы'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=products.utils.UUIDFileSystemStorage(), upload_to='product_reviews/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='pros',
            field=models.TextField(blank=True, null=True, verbose_name='Плюсы'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
