# Generated by Django 5.1.3 on 2025-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_message_chat_messenger_c_order_i_396ae2_idx_and_more'),
        ('products', '0006_remove_product_last_price_product_prev_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='messenger_c_order_i_396ae2_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='messenger_c_chat_ty_03e093_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='order',
        ),
        migrations.AddField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='products.product'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('order', 'Order Chat'), ('product', 'Product Chat'), ('support', 'Support Chat')], max_length=10),
        ),
    ]
