"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1"
).split()


# Application definition

INSTALLED_APPS = [
    'viewflow',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',

    # 'website.apps.WebsiteConfig',
    'account',
    'order',
    'products',
    'messenger.apps.MessengerConfig',

    'widget_tweaks',
    'balance.apps.BalanceConfig',
    'django_extensions',

    'drf_yasg',
    'api',
]

INSTALLED_APPS += ['corsheaders']
INSTALLED_APPS += [
    'channels',
    'django_otp',
    'django_otp.plugins.otp_totp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

DJOSER = {
    'LOGIN_FIELD': 'username',
    'USER_CREATE_PASSWORD_RETYPE': False,
    'SET_PASSWORD_RETYPE': False,
    'SEND_ACTIVATION_EMAIL': False,
    'SERIALIZERS': {
        'user_create': 'account.serializers.RegistrationOTPSerializer',
        'user': 'account.serializers.CustomUserSerializer',
        'current_user': 'account.serializers.CustomUserSerializer',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6380/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


ROOT_URLCONF = 'django_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'media/doc_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'django_app.asgi.application'

WSGI_APPLICATION = 'django_app.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {

      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'api_key_prefix': 'Bearer',
      }
   }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

POSTGRES_ENGINE = os.environ.get(
    "POSTGRES_ENGINE", "django.db.backends.sqlite3"
)
POSTGRES_DB = os.environ.get("POSTGRES_DB")
DEFAULT_DB_NAME = (
    str(BASE_DIR / "db.sqlite3")
    if POSTGRES_ENGINE == "django.db.backends.sqlite3"
    else "postgres"
)

DATABASES = {
    "default": {
        "ENGINE": POSTGRES_ENGINE,
        "NAME": POSTGRES_DB or DEFAULT_DB_NAME,
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.' +
        'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'
# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# адрес ссылки статики
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # для локалки
# папка куда собирает статику команда collectstatic
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Additional locations of static files
# Здесь ищет статику в Debug режиме
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", ""
).split()

# LOGIN_REDIRECT_URL = '/accounts/view_account/'
# LOGOUT_REDIRECT_URL = '/'
# PASSWORD_RESET_TIMEOUT_DAYS = 1

# # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.yandex.ru'

# # for docker
# # EMAIL_PORT = 465
# # EMAIL_USE_SSL = True
# # for local
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# if bool(int(os.environ.get("EMAIL_USE_SSL"))):
#     EMAIL_USE_SSL = True
# else:
#     EMAIL_USE_TLS = True
# EMAIL_PORT = os.environ.get("EMAIL_PORT")

# EMAIL_HOST_USER = 'agweather@yandex.ru'
# EMAIL_HOST_PASSWORD = os.environ.get("YANDEX_EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# SERVER_EMAIL = EMAIL_HOST_USER
# EMAIL_ADMIN = EMAIL_HOST_USER
# AUTHENTICATION_BACKENDS = ['accounts.backends.EmailBackend']

MEDIA_URL = '/media/'  # URL для доступа к медиафайлов
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Директория для хранения медиафайлов

# DOCX_TEMPLATES_ROOT = os.path.join(BASE_DIR, 'constructor/docx_templates/')
# DOCX_TEMPLATES_URL = '/constructor/docx_templates/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider's SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'
EMAIL_HOST_PASSWORD = 'your_email_password'

AUTH_USER_MODEL = 'account.CustomUser'

SESSION_COOKIE_AGE = 7 * 24 * 60 * 60  # 7 дней живут куки

SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # НЕ убираем сессию при закрытии браузера

# Добавляем логирование

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3.S3Storage",
#         "OPTIONS": {

#         },
#     },
# }?

# Настройки для работы с AWS S3
MINIO_ENDPOINT = 'localhost:9000'
MINIO_ACCESS_KEY = os.environ.get('AWS_ACCESS_KEY_ID')
MINIO_SECRET_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
MINIO_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
MINIO_USE_HTTPS = False  # Использовать HTTPS или нет

# Использование MinIO для хранения медиафайлов
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_CUSTOM_DOMAIN = f'{MINIO_BUCKET_NAME}.localhost:9000'

# Kafka (optional)
KAFKA_ENABLED = os.environ.get("KAFKA_ENABLED", "0").lower() in (
    "1", "true", "yes", "on"
)
KAFKA_BOOTSTRAP_SERVERS = os.environ.get(
    "KAFKA_BOOTSTRAP_SERVERS", "localhost:9092"
)
KAFKA_CLIENT_ID = os.environ.get("KAFKA_CLIENT_ID", "agaba-backend")
KAFKA_OPERATION_TOPIC = os.environ.get(
    "KAFKA_OPERATION_TOPIC", "operations"
)
KAFKA_ACKS = os.environ.get("KAFKA_ACKS", "all")
KAFKA_RETRIES = int(os.environ.get("KAFKA_RETRIES", "5"))
KAFKA_LINGER_MS = int(os.environ.get("KAFKA_LINGER_MS", "50"))
KAFKA_MAX_IN_FLIGHT = int(os.environ.get("KAFKA_MAX_IN_FLIGHT", "5"))
