# Generated by Django 5.1.3 on 2025-04-09 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_invoice', models.FileField(blank=True, upload_to='invoice/', verbose_name='Путь к файлу счёта')),
                ('download_link', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF файл счёта',
                'verbose_name_plural': 'PDF файлы счёта',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Счет пользователя')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
            },
        ),
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Операции пополнения')),
                ('amount_replenishment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пополнения')),
                ('payment_type', models.CharField(choices=[('account', 'Перевод по счёту'), ('card', 'Карта'), ('bonus', 'Бонус')], default='account', max_length=50, verbose_name='Тип операции пополнения')),
                ('status_operation', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Пополнен'), ('failure', 'Отказ')], default='pending', max_length=20, verbose_name='Статус операции пополнения')),
                ('number_transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер транзакции')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='account.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('withdrawal_operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID Операции вывода')),
                ('amount_withdrawal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вывода')),
                ('type_operation', models.CharField(choices=[('account', 'Вывод на счёт'), ('card', 'Вывод на карту')], default='account', max_length=7, verbose_name='Тип операции вывода')),
                ('status_operation', models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Выполнен'), ('failure', 'Отказ')], default='pending', max_length=20, verbose_name='Статус операции вывода')),
                ('number_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счёта')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('bik', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК')),
                ('ks', models.CharField(blank=True, max_length=100, null=True, verbose_name='КС')),
                ('rs', models.CharField(blank=True, max_length=100, null=True, verbose_name='РС')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='account.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вывод средств',
                'verbose_name_plural': 'Выводы средств',
            },
        ),
        migrations.CreateModel(
            name='AllOperation',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('payment_type', models.CharField(choices=[('card', 'Карта'), ('bonus', 'Бонус'), ('account', 'Перевод по счёту')], default='account', max_length=10, verbose_name='Способ оплаты')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID операции')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма операции')),
                ('type_operation', models.CharField(choices=[('replenishment', 'Пополнение'), ('withdrawal', 'Вывод'), ('order', 'Заказ')], max_length=50, verbose_name='Тип операции')),
                ('status_operation', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Отказ'), ('pending', 'Ожидание')], default='pending', max_length=20, verbose_name='Статус операции')),
                ('details', models.JSONField(default=dict, verbose_name='Детали операции')),
                ('related_operations', models.ManyToManyField(blank=True, to='balance.alloperation', verbose_name='Связанные операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('replenishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.replenishment', verbose_name='Пополнение')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.withdrawal', verbose_name='Вывод')),
            ],
            options={
                'verbose_name': 'Все операции',
                'ordering': ['-date_created'],
            },
        ),
    ]
