# Generated by Django 5.1.3 on 2025-04-10 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOperation',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order_operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Операции')),
                ('type_operation', models.CharField(choices=[('account', 'Счёт'), ('card', 'Карта'), ('balance', 'Баланс')], max_length=7, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Операция по заказам',
                'verbose_name_plural': 'Операции по заказам',
                'ordering': ['-date_created'],
            },
        ),
    ]
