# Generated by Django 5.1.3 on 2025-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_orderoperation_order_id_orderoperation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloperation',
            name='date_modifed',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
