# Generated by Django 5.1.3 on 2025-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alloperation_date_modifed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alloperation',
            old_name='date_modifed',
            new_name='date_modified',
        ),
    ]
